#!/usr/bin/env node
/**
 * Extracts the simple-icons (CC0) paths used by the service catalog into
 * src/catalog/icons.generated.ts, so only those icons are bundled.
 *
 *   node scripts/gen-icons.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);
const icons = require("simple-icons");
const { SERVICES } = await import(join(root, "src/catalog/services.ts"));

const bySlug = new Map(Object.values(icons).filter((i) => i?.slug).map((i) => [i.slug, i]));
/** Icons used outside the service catalog (push channel badges). */
const EXTRA = ["ntfy", "telegram", "discord", "wechat"];
const used = [...new Set([...SERVICES.map((s) => s.icon).filter(Boolean), ...EXTRA])].sort();
const missing = used.filter((slug) => !bySlug.has(slug));
if (missing.length) {
  console.error(`unknown simple-icons slugs: ${missing.join(", ")}`);
  process.exit(1);
}

const lines = used.map((slug) => `  ${JSON.stringify(slug)}: ${JSON.stringify(bySlug.get(slug).path)},`);
const version = JSON.parse(readFileSync(join(root, "node_modules/simple-icons/package.json"), "utf8")).version;
writeFileSync(
  join(root, "src/catalog/icons.generated.ts"),
  `// Generated by scripts/gen-icons.mjs from simple-icons ${version} (CC0-1.0). Do not edit.\n` +
    `/** 24×24 SVG path data keyed by simple-icons slug. */\n` +
    `export const BRAND_ICON_PATHS: Record<string, string> = {\n${lines.join("\n")}\n};\n`,
);
console.log(`wrote ${used.length} icons`);
